volumes:
  data:

services:
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=usersdb
      - POSTGRES_PASSWORD=Nurcan1234
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql
  myapp:
    image: postgres