volumes:
  data:

services:
  postgres_db:
    image: postgres:9.5
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=usersdb
      - POSTGRES_PASSWORD=Nurcan1234
    ports:
      - 5432:5432
    volumes:
      - data:/var/lib/postgresql
    networks:
      - default
  myapp:
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - DB_HOST=postgres_db
      - DB_USER=postgres
      - DB_NAME=usersdb
      - DB_PASSWORD=Nurcan1234
    networks:
      - default